// Build-variant feature flags.
//
// This file is REGENERATED by tools/build.py for each variant -- edits here are
// only the default used when loading the repo unpacked for development.
//
//   dist/commitment-alert/        the extension
//   dist/commitment-alert-spike/  + the CALERT-20 webNavigation spike
//
// Loaded first in both the popup (popup.html) and the content scripts
// (manifest.json content_scripts), so FEATURES is available to both.

var FEATURES = {
    // CALERT-20 spike. Off in the shipped build; on in the `spike` variant,
    // which is the only one that requests the "webNavigation" permission.
    navSpike: false
};
