// Build-variant feature flags.
//
// This file is REGENERATED by tools/build.py for each variant -- edits here are
// only the default used when loading the repo unpacked for development.
//
//   dist/commitment-alert/           telegram: false
//   dist/commitment-alert-telegram/  telegram: true
//
// Loaded first in both the popup (popup.html) and the content scripts
// (manifest.json content_scripts), so FEATURES is available to both.

var FEATURES = {
    telegram: true,
    // CALERT-20 spike. Off in both shipped builds; on in the `spike` variant,
    // which is the only one that requests the "webNavigation" permission.
    navSpike: false
};
