#!/usr/bin/env python3
"""Build the Commitment Alert extension variants.

Produces two loadable extension folders (and matching zips) from this one
source tree:

    dist/commitment-alert/            no Telegram, no external calls
    dist/commitment-alert-telegram/   Telegram notifications enabled

Deliberately a build flag rather than two branches. The `clean` branch is
already a hand-made no-Telegram build and it drifted from `main` until neither
was usable -- see docs Code-Analysis finding R1 in the vault.

Usage:
    python3 tools/build.py              # both variants
    python3 tools/build.py --variant telegram
    python3 tools/build.py --no-zip

Stdlib only, so it runs the same on the Mac and on the Windows box.
"""

import argparse
import json
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"

# Explicit include list. Deliberately NOT a copy-everything-minus-excludes:
# this repo has loose build zips, .vs/ IDE state and a 3.4 MB docx at the root,
# and an allowlist cannot accidentally ship a secret or a stray artifact.
INCLUDE_FILES = [
    "manifest.json",
    "background.js",
    "features.js",
    "DetectKeywordsEngine.js",
    "KeywordSet.js",
    "EnableDisable.js",
    "popup.js",
    "popup.html",
    "updatelog.js",
    "alert.mp3",
    "chat_melody.mp3",
    "melodyFinal.mp3",
]

INCLUDE_DIRS = [
    "icons",
    "assets",
    "libs",
]

# Hosts stripped from host_permissions when a feature is off, so a build cannot
# request access it will never use.
FEATURE_HOSTS = {
    "telegram": ["wilsonngo.com"],
}

VARIANTS = {
    "plain": {
        "dir": "commitment-alert",
        "suffix": "",
        "features": {"telegram": False},
    },
    "telegram": {
        "dir": "commitment-alert-telegram",
        "suffix": " (Telegram)",
        "features": {"telegram": True},
    },
}


def log(msg):
    print(msg, flush=True)


def render_features(features):
    lines = [
        "// GENERATED by tools/build.py -- do not edit in dist/.",
        "// Edit the source features.js (dev default) or the VARIANTS table.",
        "",
        "var FEATURES = {",
    ]
    items = sorted(features.items())
    for i, (key, value) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append("    %s: %s%s" % (key, "true" if value else "false", comma))
    lines.append("};")
    return "\n".join(lines) + "\n"


def patch_manifest(manifest, variant):
    manifest = json.loads(json.dumps(manifest))  # deep copy
    manifest["name"] = manifest["name"] + variant["suffix"]

    disabled_hosts = []
    for feature, hosts in FEATURE_HOSTS.items():
        if not variant["features"].get(feature):
            disabled_hosts.extend(hosts)

    if disabled_hosts and "host_permissions" in manifest:
        kept = [
            h for h in manifest["host_permissions"]
            if not any(bad in h for bad in disabled_hosts)
        ]
        removed = len(manifest["host_permissions"]) - len(kept)
        manifest["host_permissions"] = kept
        if removed:
            log("    stripped %d host_permission(s) for disabled features" % removed)

    return manifest


def verify(out_dir, variant):
    """Fail loudly rather than shipping a broken folder."""
    problems = []

    manifest_path = out_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    # Every file the manifest references must exist in the output.
    refs = [manifest.get("background", {}).get("service_worker")]
    refs.append(manifest.get("action", {}).get("default_popup"))
    for block in manifest.get("content_scripts", []):
        refs.extend(block.get("js", []))
    for res in manifest.get("web_accessible_resources", []):
        refs.extend(res.get("resources", []))
    refs.extend(manifest.get("icons", {}).values())

    for ref in refs:
        if not ref:
            continue
        if not (out_dir / ref.lstrip("/")).exists():
            problems.append("manifest references missing file: %s" % ref)

    features_js = (out_dir / "features.js").read_text(encoding="utf-8")
    want = "telegram: %s" % ("true" if variant["features"]["telegram"] else "false")
    if want not in features_js:
        problems.append("features.js does not contain %r" % want)

    # The no-Telegram build must not reference the relay host anywhere.
    if not variant["features"]["telegram"]:
        for path in out_dir.rglob("*.js"):
            if "libs/" in path.as_posix():
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            if "sendgram" in text and "FEATURES.telegram" not in text:
                problems.append("%s calls sendgram with no feature gate" % path.name)

    if problems:
        for p in problems:
            log("    FAIL  %s" % p)
        return False
    return True


def build(name, variant, make_zip=True):
    out_dir = DIST / variant["dir"]
    log("building %s -> dist/%s" % (name, variant["dir"]))

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for rel in INCLUDE_FILES:
        src = ROOT / rel
        if not src.exists():
            log("    FAIL  missing source file: %s" % rel)
            return False
        shutil.copy2(src, out_dir / rel)

    for rel in INCLUDE_DIRS:
        src = ROOT / rel
        if not src.exists():
            log("    FAIL  missing source dir: %s" % rel)
            return False
        shutil.copytree(src, out_dir / rel)

    (out_dir / "features.js").write_text(render_features(variant["features"]), encoding="utf-8")

    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    patched = patch_manifest(manifest, variant)
    (out_dir / "manifest.json").write_text(
        json.dumps(patched, indent=2) + "\n", encoding="utf-8"
    )

    if not verify(out_dir, variant):
        return False

    log("    ok    %s v%s" % (patched["name"], patched["version"]))

    if make_zip:
        zip_path = DIST / ("%s-%s.zip" % (variant["dir"], patched["version"]))
        if zip_path.exists():
            zip_path.unlink()
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(out_dir.rglob("*")):
                if path.is_file():
                    zf.write(path, path.relative_to(out_dir))
        log("    zip   %s (%.1f MB)" % (zip_path.name, zip_path.stat().st_size / 1e6))

    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--variant", choices=sorted(VARIANTS), help="build only this variant")
    ap.add_argument("--no-zip", action="store_true", help="skip zipping")
    args = ap.parse_args()

    DIST.mkdir(exist_ok=True)
    names = [args.variant] if args.variant else sorted(VARIANTS)

    ok = True
    for name in names:
        if not build(name, VARIANTS[name], make_zip=not args.no_zip):
            ok = False

    if not ok:
        log("\nBUILD FAILED")
        return 1

    log("\nLoad unpacked from dist/<variant>/ to test.")
    log("Reminder: the two variants need DIFFERENT signing keys, kept OUTSIDE this repo.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
