#!/usr/bin/env python3
"""Build the Commitment Alert extension variants.

Produces loadable extension folders (and matching zips) from this one source
tree:

    dist/commitment-alert/        the extension
    dist/commitment-alert-spike/  + the CALERT-20 webNavigation spike. NOT for
                                  general distribution -- it is the only build
                                  that requests the "webNavigation" permission.

Telegram was removed entirely in v2.1600, which collapsed the with/without
split back to a single shipped build. The flag machinery stays because it is
what keeps the spike out of what the team runs -- and because expressing a
variant as a build flag rather than a branch is the lesson of finding R1, where
the hand-made `clean` branch drifted from `main` until neither was usable.

Usage:
    python3 tools/build.py              # all variants
    python3 tools/build.py --variant spike
    python3 tools/build.py --no-zip

Stdlib only, so it runs the same on the Mac and on the Windows box.
"""

import argparse
import json
import re
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"

# Explicit include list. Deliberately NOT a copy-everything-minus-excludes:
# this repo has loose build zips, .vs/ IDE state and a 3.4 MB docx at the root,
# and an allowlist cannot accidentally ship a secret or a stray artifact.
INCLUDE_FILES = [
    "manifest.json",
    "background.js",
    "offscreen.html",
    "offscreen.js",
    "features.js",
    "DetectKeywordsEngine.js",
    "KeywordSet.js",
    "EnableDisable.js",
    "popup.js",
    "popup.html",
    "updatelog.js",
    "alert.mp3",
    "chat_melody.mp3",
    "melodyFinal.mp3",
]

INCLUDE_DIRS = [
    "icons",
    "assets",
    "libs",
]

# Extra manifest "permissions" entries added only when a feature is on, so a
# build never requests capability it cannot use. This matters more than it
# looks: adding a permission to a sideloaded extension can make Chrome disable
# it pending re-approval, and this team cannot afford silent downtime -- hence
# the spike lives in its own variant rather than in what everyone runs.
FEATURE_PERMISSIONS = {
    "navSpike": ["webNavigation"],
}

VARIANTS = {
    "default": {
        "dir": "commitment-alert",
        "suffix": "",
        "features": {"navSpike": False},
    },
    # CALERT-20. Not for general distribution -- run it yourself, or hand it to
    # a couple of volunteers, to collect data for a day.
    "spike": {
        "dir": "commitment-alert-spike",
        "suffix": " (webNavigation spike)",
        "features": {"navSpike": True},
    },
}


def log(msg):
    print(msg, flush=True)


def render_features(features):
    lines = [
        "// GENERATED by tools/build.py -- do not edit in dist/.",
        "// Edit the source features.js (dev default) or the VARIANTS table.",
        "",
        "var FEATURES = {",
    ]
    items = sorted(features.items())
    for i, (key, value) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append("    %s: %s%s" % (key, "true" if value else "false", comma))
    lines.append("};")
    return "\n".join(lines) + "\n"


def patch_manifest(manifest, variant):
    manifest = json.loads(json.dumps(manifest))  # deep copy
    manifest["name"] = manifest["name"] + variant["suffix"]

    for feature, extra in FEATURE_PERMISSIONS.items():
        if not variant["features"].get(feature):
            continue
        permissions = manifest.setdefault("permissions", [])
        for perm in extra:
            if perm not in permissions:
                permissions.append(perm)
                log("    added permission %r for %s" % (perm, feature))

    return manifest


def verify(out_dir, variant):
    """Fail loudly rather than shipping a broken folder."""
    problems = []

    manifest_path = out_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    # Every file the manifest references must exist in the output.
    refs = [manifest.get("background", {}).get("service_worker")]
    refs.append(manifest.get("action", {}).get("default_popup"))
    for block in manifest.get("content_scripts", []):
        refs.extend(block.get("js", []))
    for res in manifest.get("web_accessible_resources", []):
        refs.extend(res.get("resources", []))
    refs.extend(manifest.get("icons", {}).values())

    for ref in refs:
        if not ref:
            continue
        if not (out_dir / ref.lstrip("/")).exists():
            problems.append("manifest references missing file: %s" % ref)

    # The offscreen document is created at runtime, so nothing in the manifest
    # points at it and the reference check above cannot catch its absence. A
    # missing offscreen.html means invisible audio fails silently -- exactly
    # the failure this extension exists to prevent.
    if "offscreen" in manifest.get("permissions", []):
        for required in ("offscreen.html", "offscreen.js"):
            if not (out_dir / required).exists():
                problems.append("offscreen permission granted but %s is missing" % required)

    # Minimal CSS sanity check. Not a linter -- it catches one specific class of
    # mistake that is invisible everywhere else in this pipeline: a missing
    # semicolon, which makes the browser silently drop BOTH declarations.
    # This repo carried `margin-bottom: 10px padding-left: 5px;` from long
    # before the 2026-08 work and it was only spotted when a screenshot showed
    # the inputs misaligned -- node --check, the unit tests and the manifest
    # checks all pass happily while the popup renders wrong.
    for css_path in sorted(out_dir.rglob("*.css")):
        text = re.sub(r"/\*.*?\*/", "", css_path.read_text(encoding="utf-8"), flags=re.S)
        for block in re.findall(r"\{([^{}]*)\}", text):
            for declaration in block.split(";"):
                # Two "property:" pairs inside one declaration means the
                # separator between them is missing.
                if len(re.findall(r"[A-Za-z-]+\s*:", declaration)) > 1:
                    problems.append(
                        "%s: missing semicolon in %r"
                        % (css_path.relative_to(out_dir), declaration.strip()[:60])
                    )

    features_js = (out_dir / "features.js").read_text(encoding="utf-8")
    for name, enabled in variant["features"].items():
        want = "%s: %s" % (name, "true" if enabled else "false")
        if want not in features_js:
            problems.append("features.js does not contain %r" % want)

    # A permission tied to a disabled feature must not be requested, and one
    # tied to an enabled feature must be.
    granted = manifest.get("permissions", [])
    for feature, extra in FEATURE_PERMISSIONS.items():
        for perm in extra:
            enabled = bool(variant["features"].get(feature))
            if enabled and perm not in granted:
                problems.append("permission %r missing but %s is on" % (perm, feature))
            if not enabled and perm in granted:
                problems.append("permission %r requested but %s is off" % (perm, feature))

    if problems:
        for p in problems:
            log("    FAIL  %s" % p)
        return False
    return True


def build(name, variant, make_zip=True):
    out_dir = DIST / variant["dir"]
    log("building %s -> dist/%s" % (name, variant["dir"]))

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for rel in INCLUDE_FILES:
        src = ROOT / rel
        if not src.exists():
            log("    FAIL  missing source file: %s" % rel)
            return False
        shutil.copy2(src, out_dir / rel)

    for rel in INCLUDE_DIRS:
        src = ROOT / rel
        if not src.exists():
            log("    FAIL  missing source dir: %s" % rel)
            return False
        shutil.copytree(src, out_dir / rel)

    (out_dir / "features.js").write_text(render_features(variant["features"]), encoding="utf-8")

    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    patched = patch_manifest(manifest, variant)
    (out_dir / "manifest.json").write_text(
        json.dumps(patched, indent=2) + "\n", encoding="utf-8"
    )

    if not verify(out_dir, variant):
        return False

    log("    ok    %s v%s" % (patched["name"], patched["version"]))

    if make_zip:
        zip_path = DIST / ("%s-%s.zip" % (variant["dir"], patched["version"]))
        if zip_path.exists():
            zip_path.unlink()
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(out_dir.rglob("*")):
                if path.is_file():
                    zf.write(path, path.relative_to(out_dir))
        log("    zip   %s (%.1f MB)" % (zip_path.name, zip_path.stat().st_size / 1e6))

    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--variant", choices=sorted(VARIANTS), help="build only this variant")
    ap.add_argument("--no-zip", action="store_true", help="skip zipping")
    args = ap.parse_args()

    DIST.mkdir(exist_ok=True)
    names = [args.variant] if args.variant else sorted(VARIANTS)

    ok = True
    for name in names:
        if not build(name, VARIANTS[name], make_zip=not args.no_zip):
            ok = False

    if not ok:
        log("\nBUILD FAILED")
        return 1

    log("\nLoad unpacked from dist/<variant>/ to test.")
    log("Reminder: each distributed variant needs its OWN signing key, kept OUTSIDE this repo.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
